DDCNL-5044
hmrc/tamc pull request #58
Opened 2022-02-14 09:36 UTC by Dandyboyo2

2022-02-14 13:29 UTC, andrewbrown22 requested changes

2022-02-14 13:29 UTC, andrewbrown22 commented on build.sbt
> +import sbt.Keys.{scalacOptions, _}
can these imports be cleared up (line 2 and 3) line 1 is also unused.

2022-02-23 08:46 UTC, Tateni93 approved these changes

2022-02-23 08:53 UTC, andrewbrown22 approved these changes

2022-02-23 09:07 UTC, merged